#!/bin/sh
# Seed the domain-variable set that business-rule extraction slices on.
#
#   tools/factbase/domain_variables.sh --facts <dir> --enumeration <dir> --out <file>
#
# `shared/business-rule-criteria.md` defines a business rule as a condition
# that affects a DOMAIN variable. Without a concrete domain-variable set that
# definition cannot be applied, and every `if (s == null)` becomes a rule.
#
# The set is derived, not invented:
#   DB column    from the field definitions of enumerated DB object classes
#   input field  from the literal argument of parameter-reading calls
#   config key   from the literal argument of configuration-reading calls
#   DB table     from the enumeration
#
# Output: kind|name|holder|evidence

set -e
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$DIR/../lib/common.sh"

FACTS=""; ENUM=""; OUTF=""
while [ $# -gt 0 ]; do
    case "$1" in
        --facts) FACTS=$2; shift 2 ;;
        --enumeration) ENUM=$2; shift 2 ;;
        --out) OUTF=$2; shift 2 ;;
        *) die "unknown option: $1" ;;
    esac
done
[ -n "$FACTS" ] || die "--facts is required"
[ -n "$ENUM" ] || die "--enumeration is required"
[ -n "$OUTF" ] || die "--out is required"
FACTS=$(abspath "$FACTS"); ENUM=$(abspath "$ENUM")
mkdir -p "$(dirname "$OUTF")"

awk -F'|' '
    FILENAME ~ /types\.psv$/ {
        SN++; SPATH[SN] = $5; SA[SN] = $7; SB[SN] = $8; SSIMPLE[SN] = $2; next
    }
    FILENAME ~ /db-object-classes\.txt$/ { TABLE[$1] = $3; next }
    FILENAME ~ /calls\.psv$/ {
        c = $4
        # Legacy systems rarely call getParameter directly; they wrap it.
        # Match the wrappers by shape as well as by name.
        if (c == "addField" || c == "addColumn" || c == "defineField")
            SITE[$6 "|" $7] = "db-column"
        else if (c == "getParameter" || c == "getParam" || c == "getAttribute" ||
                 c == "getField" || c == "getString" || c == "getValue" ||
                 tolower(c) ~ /^(get)?(param|parm|field|attr|attribute)s?$/ ||
                 c ~ /^get[A-Z][A-Za-z0-9_]*(Param|Parm|Field|Attribute)$/)
            SITE[$6 "|" $7] = "input-field"
        else if (c == "getProperty" || c == "getConfig" || c == "getSetting")
            SITE[$6 "|" $7] = "config-key"
        next
    }
    {
        key = $1 "|" $2
        if (!(key in SITE)) next
        v = $3
        if (v !~ /^[A-Za-z_][A-Za-z0-9_.-]{1,63}$/) next
        kind = SITE[key]
        cls = "-"
        for (i = 1; i <= SN; i++)
            if (SPATH[i] == $1 && SA[i] <= $2 && $2 <= SB[i]) { cls = SSIMPLE[i]; break }
        name = (kind == "db-column") ? toupper(v) : v
        holder = (kind == "db-column" && TABLE[cls] != "") ? TABLE[cls] : cls
        k = kind "|" name "|" holder
        if (k in seen) next
        seen[k] = 1
        printf "%s|%s:%d\n", k, $1, $2
    }
' "$FACTS/types.psv" "$ENUM/db-object-classes.txt" "$FACTS/calls.psv" \
  "$FACTS/literals.psv" > "$OUTF.tmp"

awk -F'|' '$3 != "" && $3 != "UNKNOWN" { printf "db-table|%s|%s|enumeration\n", $3, $1 }' \
    "$ENUM/db-object-classes.txt" >> "$OUTF.tmp"

sort -u "$OUTF.tmp" > "$OUTF"; rm -f "$OUTF.tmp"

REPORT="$(dirname "$OUTF")/domain-variables-report.md"
{
cat <<'EOF'
# Domain Variables

Generated by `tools/factbase/domain_variables.sh`.
The input to the business-rule test in `shared/business-rule-criteria.md`.

## Counts

| Kind | Count |
|---|---|
EOF
awk -F'|' '{ c[$1]++ } END { for (k in c) printf "| %s | %d |\n", k, c[k] }' "$OUTF" | sort
cat <<'EOF'

## Variables

| Kind | Name | Holder | Evidence |
|---|---|---|---|
EOF
awk -F'|' '{ printf "| %s | `%s` | `%s` | `%s` |\n", $1, $2, $3, $4 }' "$OUTF"
cat <<'EOF'

## Using this list

A condition is a BUSINESS RULE when it reads, writes or branches on a name in
this list. A condition that touches none of them is TECHNICAL LOGIC and
belongs in the module document, not the business-rule document.

The list is derived from code, so it is incomplete wherever the code builds a
field name dynamically. Add such names by hand and record why.
EOF
} > "$REPORT"

awk -F'|' '{ c[$1]++ } END { for (k in c) printf "%s=%d ", k, c[k]; printf "\n" }' "$OUTF"
