<#
.SYNOPSIS
Seed the domain-variable set that business-rule extraction slices on.

.DESCRIPTION
`shared/business-rule-criteria.md` defines a business rule as a condition
that affects a DOMAIN variable. Without a concrete domain-variable set that
definition cannot be applied, and every `if (s == null)` becomes a rule.

The set is derived, not invented:
  DB column    from the field definitions of enumerated DB object classes
  input field  from the literal argument of parameter-reading calls
  config key   from the literal argument of configuration-reading calls
  DB table     from the enumeration

Output: kind|name|holder|evidence

.EXAMPLE
pwsh tools/powershell/factbase/domain_variables.ps1 -Facts docs\facts -Enumeration docs\enumeration -Out docs\business-rules\domain-variables.txt
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)][string]$Facts,
    [Parameter(Mandatory)][string]$Enumeration,
    [Parameter(Mandatory)][string]$Out
)

. "$PSScriptRoot/../lib/common.ps1"
Set-ToolName 'domain_variables.ps1'
$ErrorActionPreference = 'Stop'

$Facts = Get-AbsolutePath $Facts
$Enumeration = Get-AbsolutePath $Enumeration
New-ParentDirectory $Out

$spans = [System.Collections.Generic.List[object]]::new()
foreach ($l in (Read-TextLines "$Facts/types.psv")) {
    if ($l -eq '') { continue }
    $f = $l.Split('|')
    $spans.Add([pscustomobject]@{
        Path = (Get-Field $f 5); From = [int](Get-Field $f 7)
        To = [int](Get-Field $f 8); Simple = (Get-Field $f 2)
    })
}

$tableOf = @{}
foreach ($l in (Read-TextLines "$Enumeration/db-object-classes.txt")) {
    if ($l -eq '') { continue }
    $f = $l.Split('|')
    $tableOf[$f[0]] = (Get-Field $f 3)
}

# Legacy systems rarely call getParameter directly; they wrap it. Match the
# wrappers by shape as well as by name.
$site = @{}
foreach ($l in (Read-TextLines "$Facts/calls.psv")) {
    if ($l -eq '') { continue }
    $f = $l.Split('|')
    $c = (Get-Field $f 4)
    $key = "$(Get-Field $f 6)|$(Get-Field $f 7)"
    if ($c -ceq 'addField' -or $c -ceq 'addColumn' -or $c -ceq 'defineField') {
        $site[$key] = 'db-column'
    }
    elseif ($c -ceq 'getParameter' -or $c -ceq 'getParam' -or $c -ceq 'getAttribute' -or
            $c -ceq 'getField' -or $c -ceq 'getString' -or $c -ceq 'getValue' -or
            $c.ToLowerInvariant() -cmatch '^(get)?(param|parm|field|attr|attribute)s?$' -or
            $c -cmatch '^get[A-Z][A-Za-z0-9_]*(Param|Parm|Field|Attribute)$') {
        $site[$key] = 'input-field'
    }
    elseif ($c -ceq 'getProperty' -or $c -ceq 'getConfig' -or $c -ceq 'getSetting') {
        $site[$key] = 'config-key'
    }
}

$seen = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::Ordinal)
$rows = [System.Collections.Generic.List[string]]::new()
foreach ($l in (Read-TextLines "$Facts/literals.psv")) {
    if ($l -eq '') { continue }
    $f = $l.Split('|')
    $path = $f[0]
    $line = [int](Get-Field $f 2)
    $key = "$path|$line"
    if (-not $site.ContainsKey($key)) { continue }
    $v = (Get-Field $f 3)
    if ($v -cnotmatch '^[A-Za-z_][A-Za-z0-9_.-]{1,63}$') { continue }
    $kind = $site[$key]
    $cls = '-'
    foreach ($sp in $spans) {
        if ($sp.Path -eq $path -and $sp.From -le $line -and $line -le $sp.To) { $cls = $sp.Simple; break }
    }
    $name = if ($kind -eq 'db-column') { $v.ToUpperInvariant() } else { $v }
    $holder = if ($kind -eq 'db-column' -and [string]$tableOf[$cls] -ne '') { $tableOf[$cls] } else { $cls }
    $k = "$kind|$name|$holder"
    if (-not $seen.Add($k)) { continue }
    $rows.Add("${k}|${path}:$line")
}

foreach ($l in (Read-TextLines "$Enumeration/db-object-classes.txt")) {
    if ($l -eq '') { continue }
    $f = $l.Split('|')
    $t = (Get-Field $f 3)
    if ($t -ne '' -and $t -ne 'UNKNOWN') { $rows.Add("db-table|$t|$($f[0])|enumeration") }
}

$sorted = @(Sort-OrdinalUnique $rows.ToArray())
Write-TextLines $Out $sorted

$counts = @{}
foreach ($r in $sorted) {
    $k = $r.Split('|')[0]
    if ($counts.ContainsKey($k)) { $counts[$k]++ } else { $counts[$k] = 1 }
}

$report = [System.Collections.Generic.List[string]]::new()
$report.AddRange([string[]]@(
    '# Domain Variables'
    ''
    'Generated by `tools/powershell/factbase/domain_variables.ps1`.'
    'The input to the business-rule test in `shared/business-rule-criteria.md`.'
    ''
    '## Counts'
    ''
    '| Kind | Count |'
    '|---|---|'
))
$report.AddRange([string[]](Sort-Ordinal ([string[]]@(foreach ($k in $counts.Keys) { "| $k | $($counts[$k]) |" }))))
$report.AddRange([string[]]@(
    ''
    '## Variables'
    ''
    '| Kind | Name | Holder | Evidence |'
    '|---|---|---|---|'
))
foreach ($r in $sorted) {
    $f = $r.Split('|')
    $report.Add("| $($f[0]) | ``$($f[1])`` | ``$($f[2])`` | ``$($f[3])`` |")
}
$report.AddRange([string[]]@(
    ''
    '## Using this list'
    ''
    'A condition is a BUSINESS RULE when it reads, writes or branches on a name in'
    'this list. A condition that touches none of them is TECHNICAL LOGIC and'
    'belongs in the module document, not the business-rule document.'
    ''
    'The list is derived from code, so it is incomplete wherever the code builds a'
    'field name dynamically. Add such names by hand and record why.'
))
$reportPath = Join-Path (Split-Path -Parent (Get-AbsolutePath $Out)) 'domain-variables-report.md'
Write-TextLines $reportPath $report.ToArray()

$summary = ''
foreach ($k in $counts.Keys) { $summary += "$k=$($counts[$k]) " }
Write-Output $summary
