#!/bin/sh
# Group primary units into archetypes by structural similarity.
#
#   tools/factbase/archetypes.sh --repo <dir> --facts <dir> --enumeration <dir>
#       [--threshold 0.75]
#
# Legacy transaction classes are largely copy-and-paste. Documenting 458 of
# them as 458 independent programs is expensive and, for a reader, worse: what
# matters is the shape they share and the few lines where each differs.

set -e
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$DIR/../lib/common.sh"

REPO=""; FACTS=""; ENUM=""; TH=0.75
while [ $# -gt 0 ]; do
    case "$1" in
        --repo) REPO=$2; shift 2 ;;
        --facts) FACTS=$2; shift 2 ;;
        --enumeration) ENUM=$2; shift 2 ;;
        --threshold) TH=$2; shift 2 ;;
        *) die "unknown option: $1" ;;
    esac
done
[ -n "$REPO" ] || die "--repo is required"
[ -n "$FACTS" ] || die "--facts is required"
[ -n "$ENUM" ] || die "--enumeration is required"
REPO=$(abspath "$REPO"); FACTS=$(abspath "$FACTS"); ENUM=$(abspath "$ENUM")
require_file "$ENUM/transaction-classes.txt"

TMP=$(mktemp_dir); trap 'rm -rf "$TMP"' EXIT
awk -F'|' -v repo="$REPO" '{ print repo "/" $2 }' "$ENUM/transaction-classes.txt" \
    | sort -u > "$TMP/unitfiles"
[ -s "$TMP/unitfiles" ] || die "no unit files to cluster"

: > "$TMP/pairs"; : > "$TMP/clusters"; : > "$TMP/members"
xargs_files "$TMP/unitfiles" awk -v REPO="$REPO" -v TH="$TH" \
    -v PAIRS="$TMP/pairs" -v CLUSTERS="$TMP/clusters" -v MEMBERS="$TMP/members" \
    -f "$DIR/../lib/mask.awk" -f "$DIR/archetypes.awk" \
    "$FACTS/types.psv" "$FACTS/calls.psv" "$ENUM/transaction-classes.txt"

# Archetype ids: largest cluster first, ties broken by first member name.
sort -t'|' -k1,1nr -k2,2 "$TMP/clusters" \
    | awk -F'|' '{ printf "ARCH-%03d|%s|%s|%d\n", NR, $3, $4, $1 }' > "$TMP/ids"

awk -F'|' '
    NR==FNR { id[$2] = $1; rep[$2] = $3; size[$2] = $4; next }
    { printf "%s|%s|%s|%s\n", id[$1], $2, $3, $4 }' \
    "$TMP/ids" "$TMP/members" | sort -t'|' -k2,2 > "$ENUM/archetypes.txt"

NU=$(count_lines "$ENUM/archetypes.txt")
NA=$(count_lines "$TMP/ids")
NMULTI=$(awk -F'|' '$4 > 1' "$TMP/ids" | wc -l | tr -d ' ')
NIN=$(awk -F'|' '$4 > 1 { s += $4 } END { print s + 0 }' "$TMP/ids")
NSAVE=$(awk -F'|' '$4 > 1 { s += $4 - 1 } END { print s + 0 }' "$TMP/ids")

{
cat <<EOF
# Archetypes

Generated by \`tools/factbase/archetypes.sh\`.
Similarity threshold: $TH (Jaccard over 5-gram token shingles).

## Summary

| Metric | Value |
|---|---|
| Units clustered | $NU |
| Archetypes | $NA |
| Units in a multi-member archetype | $NIN |
| Full-depth documents avoidable | $NSAVE |

## How to use this

Document the representative of each multi-member archetype at full depth.
Document every other member as a delta against its representative: what
differs, and nothing else. A delta document is depth-complete when the
differences are complete.

A single-member archetype gets an ordinary full-depth document.
EOF
if [ "$NMULTI" -gt 0 ]; then
cat <<'EOF'

## Multi-member archetypes

| Archetype | Representative | Members |
|---|---|---|
EOF
awk -F'|' 'NR==FNR { if ($4 > 1) multi[$1] = 1; rep[$1] = $3; next }
    ($1 in multi) { m[$1] = m[$1] (m[$1] == "" ? "" : ", ") "`" $2 "`" }
    END { for (a in m) printf "%s|%s|%s\n", a, rep[a], m[a] }' \
    "$TMP/ids" "$ENUM/archetypes.txt" | sort \
  | awk -F'|' '{ printf "| %s | `%s` | %s |\n", $1, $2, $3 }'
cat <<'EOF'

### Member similarity

| Archetype | Member | Similarity to representative | Public methods |
|---|---|---|---|
EOF
awk -F'|' '
    NR==FNR { if ($4 > 1) multi[$1] = 1; next }
    FILENAME ~ /methods\.psv$/ { if ($7 == 1 && $6 == 0) { s = $1; sub(/^.*\./, "", s)
                                   pm[s] = pm[s] (pm[s] == "" ? "" : ", ") $2 } ; next }
    ($1 in multi) { printf "| %s | `%s` | %s | %s |\n", $1, $2, $4, (pm[$2] == "" ? "-" : pm[$2]) }' \
    "$TMP/ids" "$FACTS/methods.psv" "$ENUM/archetypes.txt"
fi
cat <<EOF

## Single-member archetypes

EOF
awk -F'|' '$4 == 1 { printf "- `%s`\n", $3 }' "$TMP/ids"
if [ -s "$TMP/pairs" ]; then
cat <<'EOF'

## Strongest pairs

| A | B | Similarity |
|---|---|---|
EOF
sort -t'|' -k1,1gr "$TMP/pairs" | head -40 \
  | awk -F'|' '{ printf "| `%s` | `%s` | %s |\n", $2, $3, $1 }'
fi
cat <<'EOF'

## Limits

Type-1 and type-2 clones only: identical code, and code that differs by
identifier or literal names. Two units that solve the same problem with
different code will not cluster, and must not be assumed equivalent because
they did not.
EOF
} > "$ENUM/archetype-report.md"

printf 'units=%s archetypes=%s multi_member=%s documents_avoidable=%s\n' \
    "$NU" "$NA" "$NMULTI" "$NSAVE"
