#!/bin/sh
# Decide Depth-Complete mechanically and write the depth report.
#
#   tools/verify/depth_checks.sh --repo <dir> --facts <dir> --docs <dir>
#       --enumeration <dir> --out <file>
#
# Exit status
#   0  Depth-Complete Rate is 100%
#   1  at least one unit failed a check
#   3  a unit in the enumeration has no document at all
#
# `shared/logic-depth.md` says a unit whose document exists but is not
# depth-complete is NOT done. This is what makes that sentence enforceable
# rather than aspirational.

set -e
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$DIR/../lib/common.sh"

REPO=""; FACTS=""; DOCS=""; ENUM=""; OUTF=""
while [ $# -gt 0 ]; do
    case "$1" in
        --repo) REPO=$2; shift 2 ;;
        --facts) FACTS=$2; shift 2 ;;
        --docs) DOCS=$2; shift 2 ;;
        --enumeration) ENUM=$2; shift 2 ;;
        --out) OUTF=$2; shift 2 ;;
        *) die "unknown option: $1" ;;
    esac
done
for v in REPO FACTS DOCS ENUM OUTF; do
    eval "[ -n \"\$$v\" ]" || die "--$(echo $v | tr 'A-Z' 'a-z') is required"
done
REPO=$(abspath "$REPO"); FACTS=$(abspath "$FACTS"); ENUM=$(abspath "$ENUM")
require_file "$ENUM/transaction-classes.txt"
mkdir -p "$(dirname "$OUTF")"

TMP=$(mktemp_dir); trap 'rm -rf "$TMP"' EXIT
awk -F'|' '$3 != "" && $3 != "UNKNOWN" { print $3 }' "$ENUM/db-object-classes.txt" \
    2>/dev/null | sort -u > "$TMP/tables.txt"
: > "$TMP/findings"; : > "$TMP/summary"; : > "$TMP/missing"

while IFS='|' read -r UNIT _; do
    [ -n "$UNIT" ] || continue
    DOC="$DOCS/$UNIT.md"
    if [ ! -f "$DOC" ]; then
        echo "$UNIT" >> "$TMP/missing"
        printf '%s|NO DOCUMENT|-|-|0|0\n' "$UNIT" >> "$TMP/summary"
        continue
    fi
    awk -F'|' -v c="$UNIT" '{ s = $1; sub(/^.*\./, "", s)
        if (s == c && $7 == 1 && $6 == 0 && $9 == 0) print }' \
        "$FACTS/methods.psv" > "$TMP/methods.psv"
    DOCREL=$(printf '%s' "$DOC" | sed "s|^$REPO/||")
    awk -v UNIT="$UNIT" -v REPO="$REPO" -v DOCREL="$DOCREL" \
        -v FINDINGS="$TMP/findings" -f "$DIR/depth_checks.awk" \
        "$TMP/methods.psv" "$TMP/tables.txt" "$DOC" >> "$TMP/summary"
done < "$ENUM/transaction-classes.txt"

TOTAL=$(count_lines "$ENUM/transaction-classes.txt")
COMPLETE=$(awk -F'|' '$2 == "DEPTH-COMPLETE"' "$TMP/summary" | wc -l | tr -d ' ')
RATE=$(awk -v c="$COMPLETE" -v t="$TOTAL" 'BEGIN { printf "%.1f", (t > 0) ? 100 * c / t : 0 }')

{
cat <<EOF
# Depth Report

Generated by \`tools/verify/depth_checks.sh\`.
Checks run: structure, excerpts, branches, fields

## Depth-Complete Rate

**$COMPLETE / $TOTAL = $RATE%**

A unit whose document exists but fails a check is counted as NOT documented,
per \`shared/logic-depth.md\`.
EOF
if [ -s "$TMP/missing" ]; then
    echo; echo "## Units with no document"; echo
    sed 's/^/- `/; s/$/`/' "$TMP/missing"
fi
cat <<'EOF'

## Per-unit result

| Unit | Status | Methods (src/doc) | Failures | Warnings |
|---|---|---|---|---|
EOF
awk -F'|' '{ printf "| `%s` | %s | %s / %s | %s | %s |\n", $1, $2, $3, $4, $5, $6 }' \
    "$TMP/summary"
if [ -s "$TMP/findings" ]; then
cat <<'EOF'

## Findings

| Severity | Check | Unit | Method | Detail | Location |
|---|---|---|---|---|---|
EOF
sort -t'|' -k1,1 -k3,3 -k2,2 "$TMP/findings" \
  | awk -F'|' '{ d = $5; gsub(/\|/, "\\|", d)
        printf "| %s | %s | `%s` | `%s` | %s | %s |\n",
               $1, $2, $3, ($4 == "" ? "-" : $4), d, ($6 == "" ? "-" : $6) }'
fi
cat <<'EOF'

## What these checks do not decide

They decide consistency with the source, not correctness of meaning. A
document that passes every check can still assign the wrong business purpose
to a correctly described method.
EOF
} > "$OUTF"

cp "$TMP/findings" "$(dirname "$OUTF")/depth-findings.psv"
printf 'Depth-Complete Rate: %s/%s = %s%%  -> %s\n' "$COMPLETE" "$TOTAL" "$RATE" "$OUTF"
[ -s "$TMP/missing" ] && exit 3
[ "$COMPLETE" = "$TOTAL" ] || exit 1
exit 0
