#!/usr/bin/env python3
"""Decide Depth-Complete mechanically and write the depth report.

    python3 tools/verify/run_depth_checks.py --repo <repo> \
        --db <repo>/docs/facts/factbase.sqlite \
        --docs <repo>/docs/modules/transactions \
        --enumeration <repo>/docs/enumeration \
        --out <repo>/docs/gap-analysis/depth-report.md

Exit status
    0  Depth-Complete Rate is 100%
    1  at least one unit failed a check
    3  a unit in the enumeration has no document at all

`shared/logic-depth.md` says a unit whose document exists but is not
depth-complete is NOT done. This tool is what makes that sentence
enforceable rather than aspirational.
"""

import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import depthlib as D

CHECKS = ("structure", "excerpts", "branches", "fields")


def enumeration_units(enumeration_dir, kind="transaction-classes.txt"):
    path = os.path.join(enumeration_dir, kind)
    units = []
    if os.path.exists(path):
        for line in D.read_lines(path):
            if line.strip():
                units.append(line.split("|")[0].strip())
    return units


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--db", required=True)
    ap.add_argument("--docs", required=True)
    ap.add_argument("--enumeration", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--only", choices=CHECKS, action="append", default=[])
    ap.add_argument("--json-out")
    args = ap.parse_args()

    repo = os.path.abspath(args.repo)
    active = args.only or list(CHECKS)
    units = enumeration_units(args.enumeration)
    known_tables = D.load_known_tables(args.enumeration)

    results, all_findings, missing_docs = {}, [], []
    for unit in units:
        doc = os.path.join(args.docs, unit + ".md")
        if not os.path.exists(doc):
            missing_docs.append(unit)
            results[unit] = {"status": "NO DOCUMENT", "fail": 0, "warn": 0}
            continue
        lines = D.read_lines(doc)
        methods = D.load_source_methods(args.db, unit)
        findings = []
        if "structure" in active:
            findings += D.check_structure(unit, lines, methods)
        if "excerpts" in active:
            findings += D.check_excerpts(unit, os.path.relpath(doc, repo),
                                         lines, repo)
        if "branches" in active:
            findings += D.check_branches(unit, lines, methods)
        if "fields" in active:
            findings += D.check_fields(unit, lines, methods, repo, known_tables)
        fails = [f for f in findings if f.severity == "FAIL"]
        warns = [f for f in findings if f.severity == "WARN"]
        all_findings += findings
        results[unit] = {
            "status": "DEPTH-COMPLETE" if not fails else "INCOMPLETE",
            "fail": len(fails), "warn": len(warns),
            "methods_in_source": len(methods),
            "methods_documented": len(D.method_sections(lines)),
        }

    complete = sum(1 for r in results.values()
                   if r["status"] == "DEPTH-COMPLETE")
    total = len(units)
    rate = (100.0 * complete / total) if total else 0.0

    out = ["# Depth Report", "",
           "Generated by `tools/verify/run_depth_checks.py`.",
           "Checks run: %s" % ", ".join(active), "",
           "## Depth-Complete Rate", "",
           "**%d / %d = %.1f%%**" % (complete, total, rate), "",
           "A unit whose document exists but fails a check is counted as NOT",
           "documented, per `shared/logic-depth.md`.", ""]
    if missing_docs:
        out += ["## Units with no document", ""]
        out += ["- `%s`" % u for u in missing_docs] + [""]
    out += ["## Per-unit result", "",
            "| Unit | Status | Methods (src/doc) | Failures | Warnings |",
            "|---|---|---|---|---|"]
    for unit in units:
        r = results[unit]
        out.append("| `%s` | %s | %s / %s | %d | %d |" % (
            unit, r["status"], r.get("methods_in_source", "-"),
            r.get("methods_documented", "-"), r["fail"], r["warn"]))
    out.append("")
    if all_findings:
        out += ["## Findings", "",
                "| Severity | Check | Unit | Method | Detail | Location |",
                "|---|---|---|---|---|---|"]
        for f in sorted(all_findings,
                        key=lambda x: (x.severity != "FAIL", x.unit, x.check)):
            out.append("| %s | %s | `%s` | `%s` | %s | %s |" % (
                f.severity, f.check, f.unit, f.method or "-",
                f.message.replace("|", "\\|"), f.location or "-"))
        out.append("")
    out += ["## What these checks do not decide", "",
            "They decide consistency with the source, not correctness of",
            "meaning. A document that passes every check can still assign the",
            "wrong business purpose to a correctly described method.", ""]

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    if args.json_out:
        with open(args.json_out, "w", encoding="utf-8") as fh:
            json.dump({"rate": rate, "complete": complete, "total": total,
                       "results": results,
                       "findings": [f.as_dict() for f in all_findings]},
                      fh, indent=2)
    print("Depth-Complete Rate: %d/%d = %.1f%%  -> %s"
          % (complete, total, rate, args.out))
    if missing_docs:
        sys.exit(3)
    sys.exit(0 if complete == total else 1)


if __name__ == "__main__":
    main()
