#!/usr/bin/env python3
"""Bind documents to the source version they were written against.

    record:  python3 tools/verify/staleness.py --repo R --db DB --docs D \
                 --enumeration E --state S --record
    check:   same command without --record

Evidence that cites `File.java:120-128` is only true of one version of that
file. Without a recorded version the citation silently rots, and a re-run has
no way to tell a document that is still correct from one that describes code
deleted two years ago.

This tool records, per unit, the sha256 of every source file its document
cites, plus the factbase commit. On a later run it reports which units are
stale and therefore need regeneration -- which is also what makes an
incremental re-run possible: regenerate the stale units, keep the rest.

Exit status
    0  nothing stale
    1  at least one unit is stale
"""

import argparse
import hashlib
import json
import os
import re
import sqlite3
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import depthlib as D


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def cited_paths(lines):
    out = set()
    for line in lines:
        for m in D.REF_RE.finditer(line):
            out.add(m.group(1))
    return out


def unit_paths(enumeration_dir):
    path = os.path.join(enumeration_dir, "transaction-classes.txt")
    out = {}
    if os.path.exists(path):
        for line in D.read_lines(path):
            if line.strip():
                parts = line.split("|")
                out[parts[0].strip()] = parts[1].strip() if len(parts) > 1 else ""
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--db", required=True)
    ap.add_argument("--docs", required=True)
    ap.add_argument("--enumeration", required=True)
    ap.add_argument("--state", required=True)
    ap.add_argument("--out")
    ap.add_argument("--record", action="store_true")
    args = ap.parse_args()

    repo = os.path.abspath(args.repo)
    con = sqlite3.connect(args.db)
    commit = dict(con.execute("SELECT key, value FROM meta")).get("commit", "UNKNOWN")
    current = dict(con.execute("SELECT path, sha256 FROM file"))
    con.close()

    units = unit_paths(args.enumeration)
    observed = {}
    for unit, src_path in units.items():
        doc = os.path.join(args.docs, unit + ".md")
        if not os.path.exists(doc):
            continue
        lines = D.read_lines(doc)
        deps = set(filter(None, [src_path])) | cited_paths(lines)
        observed[unit] = {
            "doc": os.path.relpath(doc, repo).replace(os.sep, "/"),
            "doc_sha": sha256_file(doc),
            "sources": {p: current.get(p) or (
                sha256_file(os.path.join(repo, p))
                if os.path.exists(os.path.join(repo, p)) else None)
                for p in sorted(deps)},
            "factbase_commit": commit,
        }

    if args.record:
        os.makedirs(os.path.dirname(os.path.abspath(args.state)), exist_ok=True)
        with open(args.state, "w", encoding="utf-8") as fh:
            json.dump({"commit": commit, "units": observed}, fh, indent=2,
                      sort_keys=True)
        print("recorded %d units at commit %s -> %s"
              % (len(observed), commit[:12], args.state))
        return

    previous = {}
    if os.path.exists(args.state):
        with open(args.state, encoding="utf-8") as fh:
            previous = json.load(fh).get("units", {})

    stale, fresh, new, gone = [], [], [], []
    for unit, now in sorted(observed.items()):
        before = previous.get(unit)
        if before is None:
            new.append(unit)
            continue
        changed = [p for p, sha in before["sources"].items()
                   if now["sources"].get(p) != sha]
        if changed:
            stale.append((unit, changed))
        else:
            fresh.append(unit)
    for unit in sorted(set(previous) - set(observed)):
        gone.append(unit)

    lines = ["# Staleness Report", "",
             "Generated by `tools/verify/staleness.py`.",
             "Factbase commit: `%s`" % commit, "",
             "| Class | Count |", "|---|---|",
             "| Up to date | %d |" % len(fresh),
             "| Stale (cited source changed) | %d |" % len(stale),
             "| Never recorded | %d |" % len(new),
             "| Recorded but no document now | %d |" % len(gone), ""]
    if stale:
        lines += ["## Stale units", "",
                  "Regenerate these. Every other unit may be left alone.", "",
                  "| Unit | Changed source |", "|---|---|"]
        lines += ["| `%s` | %s |" % (u, ", ".join("`%s`" % c for c in ch))
                  for u, ch in stale] + [""]
    if new:
        lines += ["## Never recorded (%d)" % len(new), ""]
        lines += ["- `%s`" % u for u in new] + [""]
    if gone:
        lines += ["## Recorded but missing (%d)" % len(gone), ""]
        lines += ["- `%s`" % u for u in gone] + [""]
    lines += ["## Incremental re-run", "",
              "    stale units  ->  regenerate",
              "    everything else  ->  keep, and keep its recorded state", ""]

    out = args.out or os.path.join(repo, "docs", "gap-analysis",
                                   "staleness-report.md")
    os.makedirs(os.path.dirname(os.path.abspath(out)), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")
    print("staleness: %d stale, %d fresh, %d new -> %s"
          % (len(stale), len(fresh), len(new), out))
    sys.exit(1 if stale else 0)


if __name__ == "__main__":
    main()
