#!/bin/sh
# Bind documents to the source version they were written against.
#
#   record: tools/verify/staleness.sh --repo R --facts F --docs D \
#               --enumeration E --state S --record
#   check:  same command without --record
#
# Evidence that cites `TransferTrx.java:120-128` is true of one version of that
# file. Without a recorded version the citation silently rots, and a re-run has
# no way to tell a document that is still correct from one that describes code
# deleted two years ago.
#
# State format: unit|docPath|docHash|srcPath=hash;srcPath=hash
#
# Exit status
#   0  nothing stale
#   1  at least one unit is stale

set -e
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$DIR/../lib/common.sh"

REPO=""; FACTS=""; DOCS=""; ENUM=""; STATE=""; OUTF=""; RECORD=0
while [ $# -gt 0 ]; do
    case "$1" in
        --repo) REPO=$2; shift 2 ;;
        --facts) FACTS=$2; shift 2 ;;
        --docs) DOCS=$2; shift 2 ;;
        --enumeration) ENUM=$2; shift 2 ;;
        --state) STATE=$2; shift 2 ;;
        --out) OUTF=$2; shift 2 ;;
        --record) RECORD=1; shift ;;
        *) die "unknown option: $1" ;;
    esac
done
for v in REPO FACTS DOCS ENUM STATE; do
    eval "[ -n \"\$$v\" ]" || die "--$(echo $v | tr 'A-Z' 'a-z') is required"
done
REPO=$(abspath "$REPO"); FACTS=$(abspath "$FACTS"); ENUM=$(abspath "$ENUM")
COMMIT=$(meta_get "$FACTS/manifest.psv" commit)
[ -n "$OUTF" ] || OUTF="$REPO/docs/gap-analysis/staleness-report.md"

TMP=$(mktemp_dir); trap 'rm -rf "$TMP"' EXIT
: > "$TMP/observed"; : > "$TMP/unresolved"

while IFS='|' read -r UNIT SRC; do
    [ -n "$UNIT" ] || continue
    DOC="$DOCS/$UNIT.md"
    [ -f "$DOC" ] || continue
    # Dependencies are the unit's own file plus every file an excerpt cites.
    # awk's match() is leftmost-longest, so a citation yields its FULL relative
    # path. A greedy sed capture yields the shortest suffix, which silently
    # records a dependency on a file that does not exist.
    { [ -n "$SRC" ] && echo "$SRC"
      awk '{ while (match($0, /[A-Za-z0-9_][A-Za-z0-9_.\/-]*\.[A-Za-z][A-Za-z0-9]*:[0-9]+[ \t]*-[ \t]*[0-9]+/)) {
                 t = substr($0, RSTART, RLENGTH); sub(/:.*$/, "", t); print t
                 $0 = substr($0, RSTART + RLENGTH) } }' "$DOC"
    } | sort -u | grep -v '^$' > "$TMP/deps"
    # Only citations that resolve become dependencies. A bare filename in a
    # prose evidence table is not a path; recording it as MISSING would put a
    # permanently unresolvable entry in the state file. Unresolved citations
    # are reported instead of being silently dropped.
    PAIRS=""
    while IFS= read -r d; do
        f="$REPO/$d"
        if [ -f "$f" ]; then
            PAIRS="$PAIRS${PAIRS:+;}$d=$(hash_file "$f")"
        else
            printf '%s|%s\n' "$UNIT" "$d" >> "$TMP/unresolved"
        fi
    done < "$TMP/deps"
    printf '%s|%s|%s|%s\n' "$UNIT" "${DOC#$REPO/}" "$(hash_file "$DOC")" "$PAIRS" \
        >> "$TMP/observed"
done < "$ENUM/transaction-classes.txt"

if [ "$RECORD" = 1 ]; then
    mkdir -p "$(dirname "$STATE")"
    { echo "# commit|$COMMIT"; sort "$TMP/observed"; } > "$STATE"
    printf 'recorded %s units at commit %s -> %s\n' \
        "$(count_lines "$TMP/observed")" "$(echo "$COMMIT" | cut -c1-12)" "$STATE"
    exit 0
fi

[ -f "$STATE" ] || : > "$TMP/emptystate"
[ -f "$STATE" ] || STATE="$TMP/emptystate"

awk -F'|' '
    FILENAME == PREV { if ($1 ~ /^#/) next
                       prev[$1] = $4; had[$1] = 1; next }
    {
        seen[$1] = 1
        if (!($1 in had)) { print "NEW|" $1 > OUTN; next }
        n = split(prev[$1], a, ";"); m = split($4, b, ";")
        for (i = 1; i <= m; i++) { split(b[i], kv, "="); now[kv[1]] = kv[2] }
        changed = ""
        for (i = 1; i <= n; i++) {
            split(a[i], kv, "=")
            if (kv[1] != "" && now[kv[1]] != kv[2])
                changed = changed (changed == "" ? "" : ",") kv[1]
        }
        split("", now)
        if (changed != "") print "STALE|" $1 "|" changed > OUTS
        else print "FRESH|" $1 > OUTF2
    }
    END { for (u in had) if (!(u in seen)) print "GONE|" u > OUTG }
' PREV="$STATE" OUTN="$TMP/new" OUTS="$TMP/stale" OUTF2="$TMP/fresh" OUTG="$TMP/gone" \
  "$STATE" "$TMP/observed"

for f in new stale fresh gone; do [ -f "$TMP/$f" ] || : > "$TMP/$f"; done
NS=$(count_lines "$TMP/stale"); NFR=$(count_lines "$TMP/fresh")
NN=$(count_lines "$TMP/new"); NG=$(count_lines "$TMP/gone")

mkdir -p "$(dirname "$OUTF")"
{
cat <<EOF
# Staleness Report

Generated by \`tools/verify/staleness.sh\`.
Factbase commit: \`${COMMIT:-UNKNOWN}\`

| Class | Count |
|---|---|
| Up to date | $NFR |
| Stale (cited source changed) | $NS |
| Never recorded | $NN |
| Recorded but no document now | $NG |
EOF
if [ "$NS" -gt 0 ]; then
cat <<'EOF'

## Stale units

Regenerate these. Every other unit may be left alone.

| Unit | Changed source |
|---|---|
EOF
awk -F'|' '{ n = split($3, p, ","); s = ""
             for (i = 1; i <= n; i++) s = s (i > 1 ? ", " : "") "`" p[i] "`"
             printf "| `%s` | %s |\n", $2, s }' "$TMP/stale"
fi
[ "$NN" -gt 0 ] && { echo; echo "## Never recorded ($NN)"; echo
                     awk -F'|' '{ printf "- `%s`\n", $2 }' "$TMP/new"; }
[ "$NG" -gt 0 ] && { echo; echo "## Recorded but missing ($NG)"; echo
                     awk -F'|' '{ printf "- `%s`\n", $2 }' "$TMP/gone"; }
if [ -s "$TMP/unresolved" ]; then
    echo; echo "## Citations that do not resolve to a file"; echo
    echo "Written as a bare filename rather than a repository-relative path."
    echo "They are not tracked for staleness."; echo
    echo "| Unit | Citation |"; echo "|---|---|"
    sort -u "$TMP/unresolved" | awk -F'|' '{ printf "| `%s` | `%s` |\n", $1, $2 }'
fi
cat <<'EOF'

## Incremental re-run

    stale units      ->  regenerate
    everything else  ->  keep, and keep its recorded state
EOF
} > "$OUTF"

printf 'staleness: %s stale, %s fresh, %s new -> %s\n' "$NS" "$NFR" "$NN" "$OUTF"
[ "$NS" -gt 0 ] && exit 1
exit 0
