#!/bin/sh
# Turn a unit document's claims into executable characterization tests.
#
#   tools/chartest/gen_skeletons.sh --docs D --enumeration E --out-dir O
#       [--package characterization]
#
# A specification nobody can run is a specification nobody can falsify.
# Michael Feathers' characterization test pins down what the legacy code
# ACTUALLY does, which is exactly what a reverse-engineered document claims.
#
# For each unit this emits one test class: one test method per row of the
# document's `Branches and Conditions` table, named after the condition and
# its outcome, with the branch's source evidence in a comment.
#
# The output does not compile against a real harness until someone supplies
# the setup. That is deliberate: the missing part is site-specific, and a
# generated test that silently passed would be worse than no test.

set -e
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$DIR/../lib/common.sh"

DOCS=""; ENUM=""; OUTD=""; PKG=characterization
while [ $# -gt 0 ]; do
    case "$1" in
        --docs) DOCS=$2; shift 2 ;;
        --enumeration) ENUM=$2; shift 2 ;;
        --out-dir) OUTD=$2; shift 2 ;;
        --package) PKG=$2; shift 2 ;;
        *) die "unknown option: $1" ;;
    esac
done
for v in DOCS ENUM OUTD; do
    eval "[ -n \"\$$v\" ]" || die "--$(echo $v | tr 'A-Z' 'a-z') is required"
done
require_file "$ENUM/transaction-classes.txt"
mkdir -p "$OUTD"

TMP=$(mktemp_dir); trap 'rm -rf "$TMP"' EXIT
: > "$TMP/index"; : > "$TMP/skipped"

while IFS='|' read -r UNIT _; do
    [ -n "$UNIT" ] || continue
    DOC="$DOCS/$UNIT.md"
    if [ ! -f "$DOC" ]; then printf '%s|no document\n' "$UNIT" >> "$TMP/skipped"; continue; fi
    awk -v UNIT="$UNIT" -v PKG="$PKG" -v OUTF="$OUTD/${UNIT}CharacterizationTest.java" \
        -f "$DIR/gen_skeletons.awk" "$DOC" >> "$TMP/index" \
      || printf '%s|generation failed\n' "$UNIT" >> "$TMP/skipped"
done < "$ENUM/transaction-classes.txt"

awk -F'|' '$2 == 0 { print $1 "|no method subsections" }' "$TMP/index" >> "$TMP/skipped"
awk -F'|' '$2 > 0' "$TMP/index" > "$TMP/written"

{
cat <<'EOF'
# Characterization Tests

Generated by `tools/chartest/gen_skeletons.sh`.

One test class per unit; one test per documented branch outcome. A generated
test fails until a harness is supplied. That failure is the honest state: the
claim is not yet verified.

| Unit | Tests | File |
|---|---|---|
EOF
awk -F'|' '{ printf "| `%s` | %s | `%sCharacterizationTest.java` |\n", $1, $2, $1 }' \
    "$TMP/written"
if [ -s "$TMP/skipped" ]; then
    echo; echo "## Skipped"; echo; echo "| Unit | Reason |"; echo "|---|---|"
    sort -u "$TMP/skipped" | awk -F'|' '{ printf "| `%s` | %s |\n", $1, $2 }'
fi
cat <<'EOF'

## Why this exists

Prose cannot be executed, so a prose specification cannot be shown to be wrong
by anything except a careful reader. These tests convert the specification's
branch claims into statements a machine can refute.
EOF
} > "$OUTD/README.md"

printf 'characterization: %s classes, %s tests, %s skipped\n' \
    "$(count_lines "$TMP/written")" \
    "$(awk -F'|' '{ s += $2 } END { print s + 0 }' "$TMP/written")" \
    "$(sort -u "$TMP/skipped" | wc -l | tr -d ' ')"
